### ISSUE TITLE
[respimg] Distinguish between x-based URL and viewport based URLs

### ISSUE THREAD

**Issue by yoavweiss** [tabatkins/specs#11]
In section 8, there's the statement "If the winning value conforms to the <x-based-urls> production".

Should there be a definition of how such conformity (or lack of) is determined? It's probably rather easy (e.g. lack of the ';' char can indicate it's not a viewport based value), but since it made me go look at the examples, I wonder if it needs to be defined.

**Comment by tabatkins** [comment]
I'm not sure what else to say here - it's whether it conforms to the grammar or not.  I dunno if there's a trivial way to distinguish them, but the two grammars should be unambiguously distinct.
