### ISSUE TITLE
[respimg] Splitting on commas

### ISSUE THREAD

**Issue by yoavweiss** [tabatkins/specs#14]
In section 12, are the unprocessed candidates split on commas? Won't that create issues with data URIs?

I think we can find the end of the candidate by searching for the next space, then find the end of the candidate resolution by searching for a comma. That way, commas in the URL are ignored, and no harm done if there's no whitespace between the candidate resolution and the next candidate.

**Comment by tabatkins** [comment]
No, it's split according to the grammar.  URLs there are restricted to not end in commas, but can otherwise contain them.
