### ISSUE TITLE
[respimg] Allow <url> base case in <viewport-urls>

### ISSUE THREAD

**Issue by igrigorik** [tabatkins/specs#18]
Viewport URLs allows us to specify the intended display width of the image based on size-viewport-list definition, followed by a list of size-based-urls. Eg..

```
<img src-1="100% (30em) 50% (50em) calc(33% - 100px); pic100.png 100, pic200.png">
```

Technically, there is no reason why we need to specify multiple size-based-urls. For example, if I wanted to use the provided size-viewport-list definitions to set the width of the asset, but if I'm always relying on the same asset, then I could do the following:

```
<img src-1="100% (30em) 50% (50em) calc(33% - 100px); pic.png 5000">
```

`5000` is an arbitrary number. The point is that there is only one choice and src-N will always download the same pic.png file, and then size it appropriately. This works.. but it doesn't feel right (tm). To cover this "base case", can we change the syntax to allow for single url, or a list of size-based-urls? That is...

```
old: <viewport-urls> = <size-viewport-list> ; <size-based-urls>
new: <viewport-urls> = <size-viewport-list> ; [ <url> | <size-based-urls> ] 
```

Above change would allow us to simplify the previous example to:

```
<img src-1="100% (30em) 50% (50em) calc(33% - 100px); pic.png">
```

This would also make for great interop story with Client-Hints: https://github.com/igrigorik/http-client-hints#interaction-with-src-n

**Comment by yoavweiss** [comment]
I think the only reason for a single URL is for Client-Hints interoperability, but such interoperability can be pretty great. :+1:

**Comment by tabatkins** [comment]
Closing, because spec is obsolete.
