### ISSUE TITLE
[respimg] Could <size-viewport-list> reside in width instead?

### ISSUE THREAD

**Issue by igrigorik** [tabatkins/specs#19]
As a thought experiment... Instead of defining <size-viewport-list> as part of src-N attribute, what if we could instead define it within existing width attribute on img? After all, that's what it's defining anyway, except for multiple breakpoints! For example, adapting the example from the spec:

``` html
<img src-1="100%; url1 400, url2 800">
<img src-1="url1 400, url2 800" width="100%">

<img src-1="100% (30em) 50% (50em) calc(33% - 100px);
              pic100.png 100, pic200.png 200, pic400.png 400">
<img width="100% (30em) 50% (50em) calc(33% - 100px)"
       src-1="pic100.png 100, pic200.png 200, pic400.png 400">

<!-- in fact, even this could work... -->
<img width="100% (30em) 50% (50em) calc(33% - 100px)"
        src="pic.png">
```

As a bonus, you could then also combine MQ art-direction:

``` html
<img width="100% (30em) 50% (50em) calc(33% - 100px)"
        src-1="(max-width: 30em) smallpic.png"
        src-2="(max-width: 50em) largepic.png">
```

In other words, since <size-viewport-list> is defining the width, why not make width smarter? Seems a bit cleaner and more intuitive? That said, I'm sure I'm overlooking three dozen edge cases here, but curious to hear your thoughts! 

/cc @yoavweiss @marcoscaceres @johnmellor

**Comment by johnmellor** [comment]
Thing is, even if you include breakpoints in your width expression, you might still need a different width expression for different media queries. For example the following srcN shows just a logo in portrait (with a size jump for devices wider than 480 DIPs), but in landscape it switches to an immersive full width photo header:

```
<img src-1="(orientation:portrait) 160px (480px) 240px; logo-xs.png 80, logo-s.png 120, logo-m.png 160, logo-l.png 240, logo-xl.png 320, logo-xxl.png 480"
     src-2="100%; photo-header-xs.jpg 160, photo-header-s.jpg 320, photo-header-m.jpg 640, photo-header-l.jpg 1280, photo-header-xl.jpg 2560">
```

There's no way to combine these two width expressions, short of creating some new microsyntax like the srcN mechanism which lets you provide a list of expressions, each with a MQ that must be matched.

**Comment by igrigorik** [comment]
Ah, right. Hmm, width-1, width-2, ..., width-N? ;-)

**Comment by tabatkins** [comment]
Closing, because spec is obsolete.
