### ISSUE TITLE
[css-aliases]  custom selector predicate limiting

### ISSUE THREAD

**Issue by bkardell** [tabatkins/specs#27]
My proposal also had a "base selector" (matches) which is useful for limiting certain cases further - for example - something like :clicked or :empty could assume things about the types (tags) of elements it applied to -- if you don't at least match this, there's really no reason to call the predicate.

I'm not sure how useful it is - in my experience a whole lot of cases wind up being just *, but if we would like to "grow proposals" it does make sense to allow prollyfills to optimize in this direction...

What about this...
CSS.registerSelector( name, observerInit, ?matches );

**Comment by tabatkins** [comment]
I'm definitely going with an object for the params, since most of them can be defaulted away.  But yes, the issue currently has a spot for the selector filter.
