### ISSUE TITLE
CSS Nesting Module Level 3 - Ugly nesting

### ISSUE THREAD

**Issue by enjikaka** [tabatkins/specs#41]
> http://tabatkins.github.io/specs/css-nesting/

Nesting with `{{` looks so ugly in the source code. Just do it like Sass and LESS.

It is a sought after functionality in CSS. But there are acquired ways to do it already. You should adapt those ways.

**Comment by jonathanKingston** [comment]
This can be closed as @tabatkins has changed the spec from `{{` to be much more aligned with LESS and Sass.
