### ISSUE TITLE
[css-font-display] Moving to "swap" should fallback elements rendered as invisible

### ISSUE THREAD

**Issue by yoavweiss** [tabatkins/specs#46]
IIUC, the current definition of the font display timeline means that elements rendered during the "block" period will remain invisible once we move to the "swap" period.

That would mean that the `block` descriptor leaves many text elements on the page invisible which is not what many browsers currently do, nor (I believe) the intention.

Am I reading the definitions incorrectly? Otherwise, I think we can add something like "when switching to this period, elements previously rendered with an invisible fallback text, will be re-rendered with a fallback font face" to the "swap" period definition.

**Comment by tabatkins** [comment]
No, you're right, there does need to be text like that.

**Comment by tabatkins** [comment]
No, never mind, deleted that comment.

The spec as it is is correct; you're reading it wrong. ^_^  The periods define how to render text using a font in a given period.  As the font advances to later periods, then, how you render it changes.  There's nothing in the definitions that implies there's some retained state between periods.

**Comment by yoavweiss** [comment]
Reading it again then :)

Is the "which dictate the rendering behavior of any elements using the font face" part is the one ensuring that all elements rendered with an invisible font face will get re-rendered once we move to "swap"?

**Comment by tabatkins** [comment]
Just the definitions of the periods is all you need.  They're all "During this period, if font is not loaded, do X; otherwise, do Y."  Thus when the font isn't in that period, those instructions stop applying, and the new period takes over.

**Comment by frivoal** [comment]
@tabatkins This issue should be closed, as the corresponding one in the csswg's repo was.
