### ISSUE TITLE
webkit-line-clamp

### ISSUE THREAD

**Issue by robcolburn** [tabatkins/specs#52]
There is a functionality of mutli-line ellipses in Webkit / Blink that doesn't seem to have any formal proposal / documentation.

Mutli-line ellipses are super useful, and currently we resort to cryptic, proprietary css or JS hacks or both.

It's been a couple years since @chriscoyier published an article on the time https://css-tricks.com/line-clampin/ .

Can the community propose that this property be helped moving forward?

https://github.com/Fyrd/caniuse/issues/1055

**Comment by robcolburn** [comment]
As an alternative, @dstorey mentioned Opera's now-deprecated Presto engine had perhaps a more elegant solution: https://github.com/Merri/ellipsis-lastline

I believe the web-development community, or at least myself, would applaud either.

**Comment by laukstein** [comment]
@robcolburn the spec proposal is discussed in https://github.com/w3c/csswg-drafts/issues/390, Chrome related task in https://bugs.chromium.org/p/chromium/issues/detail?id=305376

**Comment by robcolburn** [comment]
Grear
