### ISSUE TITLE
[css-font-display] Should the descriptor value be exposed on `FontFace`?

### ISSUE THREAD

**Issue by zachleat** [tabatkins/specs#54]
Just playing around with this on Chrome Canary and I was attempting to get a feature test working. My first instinct was to use the `FontFace` object but it doesn’t look like it exposes the font-display value:

![image](https://cloud.githubusercontent.com/assets/39355/12581501/980a11ea-c3fc-11e5-97c1-306dda0ced04.png)

Is this what you would expect? If not, I will file at issue at crbug.

**Comment by heycam** [comment]
Yes I would expect that.  I'd also expect it to be exposed on `CSSFontFaceRule` (along with the other IDL attributes like `unicodeRange`, which I think nobody implements yet anyway).

**Comment by tabatkins** [comment]
Yeah, it should be. Need to amend the specs to reflect it.

**Comment by KenjiBaheux** [comment]
@tabatkins @heycam @zachleat Could one of you confirm that we need to fix our implementation (i.e. exposing font-display on FontFace and CSSFontFaceRule)? Thanks!

cc/ @irori

**Comment by zachleat** [comment]
Looks like it’s still missing to me @KenjiBaheux

![image](https://cloud.githubusercontent.com/assets/39355/22480779/37c22242-e7b8-11e6-99dc-984570c6a604.png)
![image](https://cloud.githubusercontent.com/assets/39355/22480787/3d7c54a0-e7b8-11e6-9ad1-c6912055a267.png)
![image](https://cloud.githubusercontent.com/assets/39355/22480790/43fe8186-e7b8-11e6-9207-a325df388bc7.png)

**Comment by zachleat** [comment]
Ugh, sorry I got a new machine and I didn’t have Experimental Web Platform features enabled in my `chrome://flags`.

It looks ok to me now @KenjiBaheux, sorry for the confusion.
![image](https://cloud.githubusercontent.com/assets/39355/22480899/a3a9485a-e7b8-11e6-8390-3de966ca8dc2.png)

**Comment by tabatkins** [comment]
Fixed!
