### ISSUE TITLE
[css-when-else] Any way to avoid nested parentheses (bikeshedding?)

### ISSUE THREAD

**Issue by fvsch** [tabatkins/specs#57]
Hi,

As an author the proposed syntax with nested parentheses rustles my feathers a bit. :D

Rather than:

``` css
@when media((max-width: 60em)) {…}
```

I would rather write:

``` css
@when media(max-width: 60em) {…}
```

Similarly in this example, I wonder why `media()` needs nested parentheses but `supports()` doesn't:

``` css
@when media((width >= 400px) and (pointer: fine)) and supports(display: flex) { …}
```

Could it be written as follows?

``` css
/* A bit longer but easier to grasp what kind of test or query each fragment is */
@when media(width >= 400px) and media(pointer: fine) and supports(display: flex) { …}
```

Maybe I misunderstood the proposal's text, and both options are already included?
But if it's an either-or situation, I'd go with one function instance for each query/test.

**Comment by tabatkins** [comment]
Yup, that is already included in the grammar:

```
media( [ <media-query-list> | <mf-plain> | <mf-boolean> | <mf-range> ] )
```

The part after `<media-query-list>` are the "leaves" of the media query syntax, the stuff you put inside of parentheses.  Same goes for supports queries.

(It might make more sense to just _only_ allow the leaf syntax, so you're not accidentally nesting boolean algebras.)

**Comment by tabatkins** [comment]
Oh wait, I remember why I'm allowing it - it's so you can use a media type.  Media types are dumb and I hate them so bad. >_<

Maybe instead I'll just add a `media-type` MQ that duplicates the value of the media type, so I don't need to worry about that stupid part of the grammar.
