### ISSUE TITLE
[css-when-else] Issue 2: omitted conditions only on final @else

### ISSUE THREAD

**Issue by markbrown** [tabatkins/specs#58]
The additional requirement you refer to seems either to be not needed, or to not have the desired effect. Consider the chain:

@when A { ... }
@else B { ... }
@else { ... }      /\* no condition */
@else D { ... }
@else { ... }

Currently, this would short-circuit at the third rule, so the last two rules will never be used (this is what is desired, yes?).

If only the last @else is allowed to omit the condition, this is either a chain of three rules followed by two invalid rules, which means the same as currently, or else the whole thing is an invalid chain, which is probably not what you want.

**Comment by tabatkins** [comment]
Per spec this is a valid 5-chain, but as you correctly note, the 4th and 5th rule will never get selected.

Making it invalid (as the issue talks about) would be an authoring-level condition only, to be reported by syntax checkers and the like.
