### ISSUE TITLE
[css-when-else] interaction with @import

### ISSUE THREAD

**Issue by markbrown** [tabatkins/specs#59]
[https://drafts.csswg.org/css-cascade-4/#at-ruledef-import](https://drafts.csswg.org/css-cascade-4/#at-ruledef-import) says:

> If an @import rule refers to a valid stylesheet, user agents must treat the contents of the stylesheet as if they were written in place of the @import rule.

This suggests that a chained conditional can start in one stylesheet and continue in another. Is this the intention?

The spec should either define conditional rule chains as consecutive conditional group rules from a single stylesheet, or else, if it's really the intention, make a note of the fact that they can cross stylesheet boundaries.

**Comment by tabatkins** [comment]
Good catch; it's _definitely_ not intended that chains be able to cross @import rules.

**Comment by tabatkins** [comment]
Okay, fixed. Cascade now implicitly handles this case for me.
