### ISSUE TITLE
[css-aliases] custom --?

### ISSUE THREAD

**Issue by bkardell** [tabatkins/specs#65]
I'm not sure whether your reply over on https://github.com/skatejs/skatejs/issues/838#issuecomment-252793472 means that I did indeed misunderstand or just that there might be some wiggle room to change that still. I definitely recall that you and I discussed and I brought up in WG/www-style that css already has an 'extension' concept that everyone has to learn already, and that this works for pretty much all of css 

pseudo-classes
:-moz-focusring {}

pseudo-elements
::webkit-scrollbar {}

properties
- { -webkit-touch-callout: none; }

functions
- { border-width: -webkit-calc(..); }

media queries
media only screen and (-webkit-min-device-pixel-ratio: 1.5) ...

etc.

I know that we pitched that it would be good to have one standard 'custom' idea that people could use and that simply dropping the vendor works.  I thought WG had resolved this then, maybe not?  Or maybe we did 'in theory' or something?  In any case, we aren't using that in some places in the doc - we probably should, and it'd be nice to actually have a referenceable answer to this somewhere so since you said 'open one there' here it is.

**Comment by tabatkins** [comment]
I was responding directly to Rob about the "make an element match a custom pseudo-class without having to mutate the DOM". You're correct about naming.
