### ISSUE TITLE
[css-nesting] Selector concatenation

### ISSUE THREAD

**Issue by sbaechler** [tabatkins/specs#73]
The current spec does not mention one of the most helpful features, especially when using the BEM methodology, which is selector concatenation.

In Sass this is possible:
```
.button {
  color: black;

  &--warn {
    color: red;
  }
}
```
which compiles to:
```
.button {
  color: black;
}
.button--warn {
  color: red;
}
```
BEM is really helpful when dealing with a large codebase and this feature greatly helps reduce redundancy and long selectors.

**Comment by tabatkins** [comment]
This is intentional. We can't syntactically tell the difference between this intended concatentation, and just a plain type selector. For example, you could have written:

```
.button {
  color: black;
  &a { color: red; }
}
```

intending this to desugar to:

```
.button { color: black; }
a.button { color: red; }
```

We would need to instead have syntax that explicitly indicates concatentation somehow, like a function or something.

**Comment by sbaechler** [comment]
@tabatkins Isn't nesting just concatenation?
Your example should actually compile to:
```
.button { color: black; }
.buttona { color: red; }
```

This is a simple typo. In CSS a typo usually always breaks the selector. This should not be a reason to drop a much needed feature.

I really suggest to keep nesting generic and not artificially limit it to selectors.

**Comment by tabatkins** [comment]
No, nesting uses real selectors, and joins them properly as selectors.  In my example, the `&a` selector is saying "take the parent selector, but append an `a` type selector to the last compound selector in it", thus producing `a.button`.  It's identical to `&.foo` meaning "take the parent selector, but append a `.foo` class selector to the last compound selector in it".
