### ISSUE TITLE
[svg-params] Bring up SVG Parameters spec with CSSWG

### ISSUE THREAD

**Issue by dholbert** [tabatkins/specs#77]
Mozilla's excited about using [SVG Parameters](https://tabatkins.github.io/specs/svg-params/), or something like it, to allow SVG icons to be reused-with-color-customization.  Could we move this spec towards being an official CSSWG draft?

I'm not sure what the best first-step is there; should I file a github issue on "Adopt Tab's svg-params spec" and mark it agenda+ and give a brief explanation when it makes it to the agenda?

(Once there's some amount of consensus, I think we'd like to start implementation.  Note that we already implement something similar [not exposed to the web], for theming the Firefox toolbar icons, but we'd like to switch from that to something standardized that we can expose to all WebExtensions and to the web in general, per https://bugzilla.mozilla.org/show_bug.cgi?id=1421329#c0 )

CC @tabatkins  @jwatt @chrishtr

**Comment by tabatkins** [comment]
Yes, opening an issue with explicit implementor support would be a *wonderful* first step. ^_^

**Comment by chrishtr** [comment]
> I'm not sure what the best first-step is there; should I file a github issue on "Adopt Tab's svg-params spec" and mark it agenda+ and give a brief explanation when it makes it to the agenda?

+1 to this approach. The resolution would be to bring this work item into the CSSWG and chosose a spec to edit it into.

**Comment by dholbert** [comment]
Great, thanks for the feedback! I opened https://github.com/w3c/csswg-drafts/issues/6988
