### ISSUE TITLE
[css-anchor-position] Various questions + concerns

### ISSUE THREAD

**Issue by ddamato** [tabatkins/specs#78]
Just read the updated spec today, it's looking good! I have some thoughts:

## dashed-ident

Is there a reason why the `anchor-name` is a `<dashed-ident>`? If we're going to use at-rules, I would figure that the construction would have been similar to `@keyframes`, where the name is just provided directly after the `@keyframes` keyword.

```css
@position-fallback my-button { ... }
```

I noticed some other specs are doing this for other at-rules, so maybe its just something we're migrating to?

## Relating dimensions

Could we reduce the `anchor()` and `anchor-size()` functions to one `anchor()` function which provides the value based on the second argument? I imagine this would be helpful so we don't need to recall a different function specifically for dimensions.

```css
.flyout {
  width: anchor(my-button, width);
  bottom: anchor(my-button, top);
}
```

Admittedly, I'm not entirely sure we need this because the most of the values that I'd normally use for positioning are already relative to the relatively positioned parent of the anchor.

```css
.flyout {
  width: 100%;
  bottom: 100%;
}
```

I will say though that I've definitely come across areas where I wanted to use the dimensions of one element to inform another. Though I wouldn't want this restricted to absolutely positioned elements. Overall, I don't think this feature should be specific to anchor positioning.

## Overflow

I see this in the spec at the moment:

> To determine which entry is selected, [iterate](https://infra.spec.whatwg.org/#list-iterate) over the [position fallback list](https://tabatkins.github.io/specs/css-anchor-position/#position-fallback-list), applying the properties of each entry in turn according to the standard cascade rules, and determining whether or not the element’s [margin box](https://drafts.csswg.org/css-box-4/#margin-box) overflows its [containing block](https://drafts.csswg.org/css-display-3/#containing-block).

This sounds like we can select the containing block for the comparison to occur against. [According to MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block#identifying_the_containing_block):

> 1. If the position property is static, relative, or sticky, the containing block is formed by the edge of the content box of the nearest ancestor element that is either a block container (such as an inline-block, block, or list-item element) or establishes a formatting context (such as a table container, flex container, grid container, or the block container itself).
> 1. If the position property is absolute, **the containing block is formed by the edge of the padding box of the nearest ancestor element that has a position value other than static (fixed, absolute, relative, or sticky)**.
> 1. If the position property is fixed, the containing block is established by the [viewport](https://developer.mozilla.org/en-US/docs/Glossary/Viewport) (in the case of continuous media) or the page area (in the case of paged media).
> 1. If the position property is absolute or fixed, the containing block may also be formed by the edge of the padding box of the nearest ancestor element that has the following:
>     1. A [transform](https://developer.mozilla.org/en-US/docs/Web/CSS/transform) or [perspective](https://developer.mozilla.org/en-US/docs/Web/CSS/perspective) value other than none
>     1. A [will-change](https://developer.mozilla.org/en-US/docs/Web/CSS/will-change) value of transform or perspective
>     1. A [filter](https://developer.mozilla.org/en-US/docs/Web/CSS/filter) value other than none or a will-change value of filter (only works on Firefox).
>     1. A [contain](https://developer.mozilla.org/en-US/docs/Web/CSS/contain) value of paint (e.g. contain: paint;)
>     1. A [backdrop-filter](https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter) other than none (e.g. backdrop-filter: blur(10px);) 

I'm most concerned about the second point. Since we are expecting to absolutely position the anchor against a relative parent. The parent would create a containing block. How could the comparison occur if the flyout (margin box) is positioned outside of the anchor (containing block)? The overflow would be immediate.

I think instead we should be comparing against the closest `overflow` container based on values provided. I also imagine there will be cases where we might want the flyout to appear outside an overflow container, and cases where we might not. I think having different behaviors using `overflow` values would be helpful here.

## at-rule name

I'm not sure if `@position-fallback` is the right term to describe the list within. I would assume a fallback would be a default once all the attempts are made; so technically the position after all of the list has been exhausted. I would instead call this `@position-attempts`:

```css
@position-attempts my-button {
  @try { ... }
}
```

Though I can also see that the relationship between the at-rule and the name isn't correct. The anchor isn't trying to position anything, only the resulting flyout is attempting new positions. Using the possibility of `overflow` above, we might want to introduce the idea of an "intersection query".

```css
@intersection (top: 0%) {
  .flyout {
    top: anchor(my-button, bottom);
  }
}
```

The intersection query looks at the closest `overflow` ancestor and when an element within intersects the top of the ancestor, then trigger the rule. This aligns directly with [the `IntersectionObserver` API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API). In this case I'm implicitly using the overflow ancestor as the root, but perhaps we borrow from [Container Queries](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Container_Queries).

```css
.scroll-container {
  overflow: auto;
  container-type: intersection;
  container-name: root;
}

@intersection root (top: 0%) {
  .flyout {
    top: 100%;
  }
}
```

**Comment by tabatkins** [comment]
> dashed-ident

Whether we use custom-ident or dashed-ident is purely a question of whether we think there will be parsing ambiguities, and/or if we're gonna mix CSS-defined keywords into the value space. Right now I'm just being somewhat defensive here; if it turns out to not be problematic, I'll shift it back to custom-ident.

> Relating dimensions

I originally wrote it as a single function, but the fact that the anchor-side keywords are only usable in the inset properties, while the anchor-size keywords are usable more widely, made me split it. Feels easier to learn the validity split when they're separate functions, rather than just a set of keywords one way or the other.

Their grammars might also diverge a little more over time, which again is easier to learn and to specify as separate fucntions.

> Overflow

If what you want is to fallback based on the viewport (which is indeed the common case), you'll make the anchoring element fixpos, not abspos. Then the viewport is its containing block and you get the desired behavior. (It can also target more elements with anchor() then, since its containing block is above the root element and it paints after everything.)

> at-rule name

I'm not attached to any name in particular, but I believe that "fallback" is reasonable here - they're fallback positions if the original position is unacceptable.

**Comment by ddamato** [comment]
Thanks for the insight! A few responses:

> If what you want is to fallback based on the viewport (which is indeed the common case), you'll make the anchoring element fixpos, not abspos. Then the viewport is its containing block and you get the desired behavior. (It can also target more elements with anchor() then, since its containing block is above the root element and it paints after everything.)

It's less about the viewport and more about generic overflow containers that we may want flyout elements to be contained inside of and some where we might not. In this way I think it's less about the anchor or flyout and more about the behavior in relation to ancestors. That's why I was recommending the `IntersectionObserver` approach, where the `root` element is defined on init and then elements can register to listen against instance.

> I'm not attached to any name in particular, but I believe that "fallback" is reasonable here - they're fallback positions if the original position is unacceptable.

Not sure if I read the spec incorrectly, but I could have swore the `dashed-ident` was the name of the anchor in the `@position-fallback` declaration. That's where my feedback was coming from. Reading the spec now, it seems better that it's a property on the flyout (ie. the element being positioned).

**Comment by tabatkins** [comment]
The issue with registering to arbitrary containers is that we're trying to (a) avoid having to do cycle detection, and (b) make sure we can do anchoring in a single pass during normal layout, so it's always correct, rather than being a frame delayed. The current rules for how you can anchor and what fallback responds to are designed around that and work well; going more generic would defeat one or both of the goals above.

Right now we've basically got two choices - you can either be contained by your normal abspos container, and be limited to anchors also within that container, or you can be contained by the viewport (by becoming fixpos) and aren't limited almost at all. We think those will serve the vast majority of cases, but I'd be very interested in seeing examples where you want to do something that doesn't work under those constraints.

> Reading the spec now, it seems better that it's a property on the flyout (ie. the element being positioned).

Right, probably just a misread then. ^_^

**Comment by ddamato** [comment]
Hmm, some clarification. When you say "contained" by your abs/fixpos container, are you saying that the elements (anchor and flyout) are expected to be in an abs/fixpos container themselves? I was expecting the anchor at the very least to be in document flow while the flyout would be itself abs/fixpos. Am I reading that wrong?

As for an example, admittedly I don't have anything practical at hand. I just recall having to do a great deal of gymnastics to fight against `overflow: auto` and flyouts in the past. Requirements would expect that a flyout be visible outside of one frame but clipped in another within the same experience. Perhaps, the answer here is just to use a new containing block (`translateZ(0)` trick) to make the fixpos act like abspos for this frame.

**Comment by tabatkins** [comment]
By "abspos container" I mean an element that generates an abspos containing block. That is, an element with `position: relative`, or a number of other possibilities that trigger this. I didn't mean being a container that was abspos, but I recognize my wording was unclear to someone not already steeped in our jargon. ^_^

**Comment by ddamato** [comment]
Ah perfect thank you, I understand that. All issues addressed, closing.
