### ISSUE TITLE
[css-anchor-position] Sizing popups relative to anchor _and_ viewport bounds

### ISSUE THREAD

**Issue by jelbourn** [tabatkins/specs#79]
In the Angular ecosystem, we have a module, `@angular/cdk/overlay`, that deals with this popup problem space. [Relevant positioning code](https://github.com/angular/components/blob/main/src/cdk/overlay/position/flexible-connected-position-strategy.ts), [development demo](https://jelbourn-dev.web.app/connected-overlay).

One key feature of our code here is that we can control the _size_ of the popup based on the amount of space available in the viewport. This is important for uses cases involving long menus/comboboxes, where you want the popup to be as large as possible without extending beyond the bounds of the viewport. At the same time, if the content of the popup is smaller, it naturally fits those contents:

A popup with 100 items takes up all available space between the anchor and the viewport boundary:
![image](https://user-images.githubusercontent.com/838736/172236662-1cfb91a7-67b9-407e-9484-51e53e22624e.png)

While a popup with 5 items naturally fits its content:
![image](https://user-images.githubusercontent.com/838736/172236834-8c6a5319-9268-4679-b264-7a79288366f4.png)

From reading the draft spec, it seems like there's a way to size the popup relative to the size of the anchor, but it's not clear to me if you could accomplish this behavior that ties to the viewport bounds.

**Comment by jelbourn** [comment]
Think about this more- would something roughly like this work if the `anchor-size` function were changed to support inset properties?
```css
.panel {
  top: anchor(origin, bottom);
  max-height: calc(100vh - anchor-size(origin, bottom));
}
```

**Comment by tabatkins** [comment]
Make the anchored element fixpos, and 0%/100% correspond to the viewport edges, while anchor() can correspond to whatever element you're caring about.

("Make it fixpos" is the solution to most anchoring problems, I believe.)

In this case, you'd do:

```css
.panel {
  top: anchor(--origin bottom);
  bottom: 100%;
  align-self: start;
  max-height: 100%;
}
```

That is, set up your inset-modified containing block (IMCB) to start at the bottom of the --origin element and extend to the bottom of the screen, set a max-height of at most that full distance, and use align-self to align it to the top of the IMCB when it's shorter than that.

**Comment by jelbourn** [comment]
@tabatkins wouldn't setting `bottom: 100%` always make the popup extend to the viewport boundary, rather than only when the content would be large enough to warrant it?

**Comment by tabatkins** [comment]
If done by itself, yes; that's what the `align-self: start` is there for. It changes the behavior of abspos from "stretch between both explicitly-set edges" (today's default) to "auto-size, then align within the rectangle defined by the edges".

(That's [per spec](https://drafts.csswg.org/css-align/#align-abspos), at least. Browsers haven't caught up to the spec in this regard yet, but will. Chrome might do it later this year (tho no promises on timeline).)
