### ISSUE TITLE
[css-anchor-position] You don't always want overflow calculation based on the containing block

### ISSUE THREAD

**Issue by jelbourn** [tabatkins/specs#80]
The draft spec currently reads
> allowing multiple different sizes/positions to be tried out sequentially until one is found that fits within the element's [containing block](https://drafts.csswg.org/css-display-3/#containing-block).

However, there are cases (perhaps most cases?) where escaping the bounds of the containing block is desirable, but you want the popup to remain within the viewport. The best example of this is a modal dialog that contains a menu:
![image](https://user-images.githubusercontent.com/838736/172240036-77008e66-c2f9-4ebe-8c8d-2ef77853e50c.png)

_[(example code in StackBlitz)](https://stackblitz.com/edit/angular-wmkvbk?file=src%2Fapp%2Fdialog-elements-example-dialog.html)_

Not sure if there's some nuance I'm missing here, but I believe this is a pretty common use case.

**Comment by tabatkins** [comment]
This should usually be addressed by making the popup fixpos; its containing block is then the viewport. (And as a side-effect, it's now capable of anchoring against anything else in the document, as fixposes get painted after everything non-fixpos.)

**Comment by jelbourn** [comment]
Ahh, got it. Might be useful to mention that in the spec.
