### ISSUE TITLE
[css-anchor-position] Spacing from viewport/containing block boundary

### ISSUE THREAD

**Issue by jelbourn** [tabatkins/specs#81]
In the Angular ecosystem, we have a module, `@angular/cdk/overlay`, that deals with this popup problem space. [Relevant positioning code](https://github.com/angular/components/blob/main/src/cdk/overlay/position/flexible-connected-position-strategy.ts), [development demo](https://jelbourn-dev.web.app/connected-overlay).

One feature of our code is to allow specifying a "viewport margin", i.e., a minimum amount of space between the popup and the viewport boundary. There are two main reasons for this:
* Prevent the popup's `box-shadow` from being clipped by the viewport edge
* More clear delineation prevents the pop-up from appearing clipped to the end user

From a positioning behavior standpoint, setting this viewport margin makes the code treat the viewport as effectively that much smaller than its actual position. It's not clear to me from the draft spec whether you'd be able to easily accomplish something similar.

**Comment by tabatkins** [comment]
Yup, if the anchoring element is fixpos, then the inset properties start at the viewport bounds, given "0" values. You can then set up this sort of margin by making them non-zero, possible combined with `max()` if you're also anchoring that side to something.
