### ISSUE TITLE
[respimg] following the media query?

### ISSUE THREAD

**Issue by marcoscaceres** [tabatkins/specs#9]
The spec says:

> If it returns true, let winning value be the value of this attribute following the media query and abort this sub-algorithm. 

I don't understand what "following the media query" means? 

Does it just mean?:

```
var winningValue = attr.value;
```

**Comment by tabatkins** [comment]
Say you have `src1="(foo: bar) and (baz:qux) url1 1x, url2 2x"`.

The part "following the media query" is "url1 1x, url2 2x".

I can try to clarify that more - I'm attempting to avoid an explicit parser, but may have to end up doing that anyway. :/

**Comment by marcoscaceres** [comment]
thanks! yeah, I noticed that the parsing is a bit lose compared to srcset.

**Comment by yoavweiss** [comment]
Related question: Is there an easy way to define parsing out MQs, while delegating the real MQ parsing to the CSS parser?

Perhaps relying on parenthesis in some way? Anything between the first '(' and the last ')'?

Ideally, I'd want to be able to say "MQs start here and end here" without looking into them.

**Comment by tabatkins** [comment]
@yoavweiss Yes, though you do need to do a little bit of parsing yourself.  Nothing like actually parsing MQs, just enough to match parens.  Look for a list of 0 or more parenthesized groups, separated by "and" keywords.  As soon as you see some other kind of top-level value, you're out of the MQs.

**Comment by tabatkins** [comment]
Closing, because spec is obsolete.
